# Generated by Django 3.2.9 on 2021-11-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(choices=[('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('kolkata', 'Kolkāta'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('pune', 'Pune'), ('ahmedabad', 'Ahmedabad'), ('patna', 'Patna'), ('hyderabad', 'Hyderabad'), ('bhuj', 'Bhuj'), ('vadodara', 'Vadodara'), ('dehradun', 'Dehradun')], default='Mumbai', max_length=50),
        ),
    ]
