# Generated by Django 3.2.9 on 2021-11-23 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(choices=[('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('kolkata', 'Kolkāta'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('pune', 'Pune'), ('ahmedabad', 'Ahmedabad'), ('patna', 'Patna'), ('hyderabad', 'Hyderabad'), ('bhuj', 'Bhuj'), ('vadodara', 'Vadodara'), ('dehradun', 'Dehradun')], default='Mumbai', max_length=50)),
                ('state', models.CharField(choices=[('delhi', 'Delhi'), ('mumbai', 'Mumbai'), ('kolkata', 'Kolkāta'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('pune', 'Pune'), ('ahmedabad', 'Ahmedabad'), ('patna', 'Patna'), ('hyderabad', 'Hyderabad'), ('bhuj', 'Bhuj'), ('vadodara', 'Vadodara'), ('dehradun', 'Dehradun')], default='Maharashtra', max_length=50)),
                ('Area', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_pics', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.post')),
            ],
        ),
    ]
