# Generated by Django 3.2.9 on 2021-11-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='amenities',
            field=models.CharField(default='[]', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
