# Generated by Django 3.2.9 on 2021-11-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211124_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
