# Generated by Django 3.2.9 on 2021-11-24 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_post_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
