# Generated by Django 3.2.9 on 2021-11-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_reviews_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Img',
        ),
    ]
